/**
 * CLI config example
 * markdown.config.js as default name
 */
module.exports = {
  transforms: {
    /* Match AUTO-GENERATED-CONTENT (LOLZ) */
    LOLZ(content, options) {
      return `This section was generated by the cli config markdown.config.js file`
    }
  },
  callback: function () {
    console.log('done')
  }
}
