const fs = require('fs')
const path = require('path')
const { test } = require('uvu')
const assert = require('uvu/assert')
const { deepLog } = require('../logs')
const { parseMarkdown } = require('./parse')
const { findLinks } = require('./find-links')
const { findFrontmatter } = require('./find-frontmatter')

const FILE_PATH = path.join(__dirname, 'fixtures/file-with-links.md')
// const FILE_PATH = path.join(__dirname, 'fixtures/2022-01-22-date-in-filename.md')
const fileContents = fs.readFileSync(FILE_PATH, 'utf-8')

test('parseMarkdown API', async () => {
  const res = parseMarkdown(fileContents, { filePath: FILE_PATH })
  deepLog(res.links)
  assert.is(typeof res, 'object')
  assert.is(typeof res.ast, 'object')
  assert.is(typeof res.data, 'object')
  assert.is(typeof res.content, 'string')
  assert.is(typeof res.codeBlocks, 'object')
  assert.is(Array.isArray(res.errors), true)
})

// test('File have correct extensions', async () => {
//   const { data } = findFrontmatter(fileWithLinks, FILE_PATH)
//   console.log('frontmatter data', data)
//   const links = findLinks(fileWithLinks, { frontmatter: data })
//   // console.log('links', links)
//   // console.log('FILE_PATH', FILE_PATH)
//   // console.log('parseMarkdown')
//   // const x = parseMarkdown(fileWithLinks, { filePath: FILE_PATH })
//   // deepLog(x)
// })

test.run()